export const GatewayEvents = {
  // Connection lifecycle
  READY: 'READY',
  RESUMED: 'RESUMED',

  // Guild events
  GUILD_CREATE: 'GUILD_CREATE',
  GUILD_UPDATE: 'GUILD_UPDATE',
  GUILD_DELETE: 'GUILD_DELETE',

  // Channel events
  CHANNEL_CREATE: 'CHANNEL_CREATE',
  CHANNEL_UPDATE: 'CHANNEL_UPDATE',
  CHANNEL_DELETE: 'CHANNEL_DELETE',
  CHANNEL_PINS_UPDATE: 'CHANNEL_PINS_UPDATE',

  // Message events
  MESSAGE_CREATE: 'MESSAGE_CREATE',
  MESSAGE_UPDATE: 'MESSAGE_UPDATE',
  MESSAGE_DELETE: 'MESSAGE_DELETE',
  MESSAGE_DELETE_BULK: 'MESSAGE_DELETE_BULK',
  MESSAGE_REACTION_ADD: 'MESSAGE_REACTION_ADD',
  MESSAGE_REACTION_REMOVE: 'MESSAGE_REACTION_REMOVE',

  // Guild member events
  GUILD_MEMBER_ADD: 'GUILD_MEMBER_ADD',
  GUILD_MEMBER_REMOVE: 'GUILD_MEMBER_REMOVE',
  GUILD_MEMBER_UPDATE: 'GUILD_MEMBER_UPDATE',
  GUILD_MEMBERS_CHUNK: 'GUILD_MEMBERS_CHUNK',

  // Guild role events
  GUILD_ROLE_CREATE: 'GUILD_ROLE_CREATE',
  GUILD_ROLE_UPDATE: 'GUILD_ROLE_UPDATE',
  GUILD_ROLE_DELETE: 'GUILD_ROLE_DELETE',

  // Guild ban events
  GUILD_BAN_ADD: 'GUILD_BAN_ADD',
  GUILD_BAN_REMOVE: 'GUILD_BAN_REMOVE',

  // Presence & typing
  PRESENCE_UPDATE: 'PRESENCE_UPDATE',
  TYPING_START: 'TYPING_START',

  // Voice events
  VOICE_STATE_UPDATE: 'VOICE_STATE_UPDATE',
  VOICE_SERVER_UPDATE: 'VOICE_SERVER_UPDATE',

  // Invite events
  INVITE_CREATE: 'INVITE_CREATE',
  INVITE_DELETE: 'INVITE_DELETE',

  // User events
  USER_UPDATE: 'USER_UPDATE',

  // Relationship events
  RELATIONSHIP_ADD: 'RELATIONSHIP_ADD',
  RELATIONSHIP_REMOVE: 'RELATIONSHIP_REMOVE',

  // Server events
  SERVER_RESTART: 'SERVER_RESTART',
} as const;

export type GatewayEvent = (typeof GatewayEvents)[keyof typeof GatewayEvents];
